server:
  port: 5000
  servlet:
    context-path: /notecard

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/local-db?currentSchema=notecard1
    username: postgres
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: false
    hibernate:
      ddl-auto: create-drop
